# Generated by Django 5.2.5 on 2025-09-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
