# Generated by Django 5.0.6 on 2025-09-15 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('status', models.CharField(default='queued', max_length=20)),
                ('progress', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='testcase.testcase')),
            ],
        ),
    ]
