# Generated by Django 5.0.6 on 2025-11-04 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0010_alter_project_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.project')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.testcase')),
            ],
        ),
    ]
